# Generated by Django 5.1.4 on 2025-02-14 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_otp_expires_at'),
        ('swipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_user1', to='Users.users'),
        ),
        migrations.AlterField(
            model_name='match',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_user2', to='Users.users'),
        ),
        migrations.AlterField(
            model_name='swipe',
            name='swiped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swiped', to='Users.users'),
        ),
        migrations.AlterField(
            model_name='swipe',
            name='swiper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swiper', to='Users.users'),
        ),
    ]
