# Generated by Django 5.1.4 on 2025-02-14 03:46

import datetime
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('otp_digits', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2025, 2, 14, 3, 56, 0, 789394, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('dateofbirth', models.DateField()),
                ('bio', models.CharField(max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'other')])),
                ('visibility', models.BooleanField(default=True)),
                ('orientation', models.CharField(choices=[('s', 'straight'), ('h', 'homosexual'), ('p', 'pansexual'), ('b', 'bisexual')])),
                ('intrests', multiselectfield.db.fields.MultiSelectField(choices=[('reading', 'Reading'), ('hiking', 'Hiking'), ('coding', 'Coding'), ('dancing', 'Dancing')], max_length=29)),
                ('location', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(null=True, upload_to='profile_pics/')),
            ],
        ),
    ]
