# Generated by Django 5.1.4 on 2025-02-14 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 14, 3, 56, 22, 887208, tzinfo=datetime.timezone.utc)),
        ),
    ]
