# Generated by Django 5.1.4 on 2025-02-14 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 14, 4, 9, 57, 528419, tzinfo=datetime.timezone.utc)),
        ),
    ]
