# Generated by Django 5.1.4 on 2025-02-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_alter_otp_expires_at'),
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='story',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_stories', to='Users.users'),
        ),
    ]
